version: '3.8'

services:

  nodejs:
    container_name: discord-bot
    build:
      context: .
      dockerfile: "./Docker/Dockerfile"
    restart: unless-stopped
    environment:
      NODE_ENV: development
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules